#!/bin/bash

echo Copyright 2017 By James Cozzi \(jcoz00\)
echo Please Put The Path To  Your Uncompiled Folder…
read uncompiledPath
echo Removing .DS_Store Files…
cd $uncompiledPath && find . -name '*.DS_Store' -type f -delete
sleep 1
echo Compiling Folder to Deb…
dpkg-deb -Zgzip -b $uncompiledPath
echo Done!