#!/bin/bash
#         _                  ____  ____ 
#        (_)________  ____  / __ \/ __ \
#       / / ___/ __ \/_  / / / / / / / /
#      / / /__/ /_/ / / /_/ /_/ / /_/ / 
#   __/ /\___/\____/ /___/\____/\____/  
#  /___/                                
#©2017-2019 by James Cozzi All rights reserved

echo Please Put The Path To Your Uncompiled Folder…
read -r uncompiledPath
echo Removing .DS_Store Files…
cd $uncompiledPath && find . -name '*.DS_Store' -type f -delete
sleep 1
echo Compiling Folder to Deb…
dpkg-deb -Zgzip -b $uncompiledPath
sleep 2
echo Done!